---
title: Cytovale
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
email: info@cytovale.com
description: 'CytoVale is pioneering a new class of biomarkers and applying this first to sepsis, a condition whose early detection dramatically improves patient outcomes and reduces treatment cost.

'
baseurl: 
url: http://cytovale.com
markdown: kramdown
permalink: pretty
